version: '2'
services:

  db:
    image: mariadb:latest
    container_name: wordpres_db_prod
    restart: always
    volumes:
       - ./db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 0ew,jwfh8iy[

    networks:
      - wp_network


  wordpress:
    depends_on:
      - db
    image: wordpress:latest
    container_name: wordpres_web_prod
    restart: always
    volumes:
      - ./www/:/var/www/html/
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: root
      WORDPRESS_DB_PASSWORD: 0ew,jwfh8iy[
      WORDPRESS_DB_NAME: db_wordpress
      #      WORDPRESS_TABLE_PREFIX: dx36fd_
    ports:
      - 80:80
    networks:
      - wp_network

networks:
  wp_network: